"""
Biomedical entity and relationship extraction for BioOS.

Scientific text is sent to a locally running language model through
Ollama and converted into structured research objects and relationships.
"""

import json
import os
from pathlib import Path

import requests
from dotenv import load_dotenv

from schemas import ExtractionResult


# ---------------------------------------------------------------------------
# Environment configuration
# ---------------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent
ENV_PATH = BASE_DIR / ".env"

load_dotenv(ENV_PATH)


# ---------------------------------------------------------------------------
# Ollama configuration
# ---------------------------------------------------------------------------

OLLAMA_URL = os.getenv(
    "OLLAMA_URL",
    "http://localhost:11434/api/chat"
)

OLLAMA_MODEL = os.getenv(
    "OLLAMA_MODEL",
    "gemma3:4b"
)

# ---------------------------------------------------------------------------
# Extraction prompt
# ---------------------------------------------------------------------------

EXTRACTION_PROMPT = """
You are a biomedical entity-extraction engine for a research graph tool.

Given a snippet of scientific text, extract the most important biomedical
entities and relationships.

Respond with STRICT JSON ONLY.
Do not include markdown fences, commentary, or explanatory text.

Use exactly this schema:

{
  "title": "short title for this text (max 8 words)",
  "objects": [
    {
      "tempId": "o1",
      "type": "Gene",
      "name": "SPP1",
      "summary": "one sentence, maximum 20 words"
    }
  ],
  "relationships": [
    {
      "from": "o1",
      "to": "o2",
      "type": "ASSOCIATED_WITH"
    }
  ]
}

Allowed object types:
- Gene
- Drug
- Pathway
- Finding
- Hypothesis
- Disease

Allowed relationship types:
- SUPPORTS
- CONTRADICTS
- ASSOCIATED_WITH
- MEASURES
- TARGETS
- PART_OF

Rules:

1. Extract at most 8 objects.
2. Extract at most 8 relationships.
3. Only extract information clearly stated or strongly implied by the text.
4. Use canonical short names where possible, especially gene symbols.
5. Every object must have a unique tempId such as o1, o2, o3.
6. Relationships must only reference tempIds present in objects.
7. Do not invent biomedical claims absent from the source text.
8. Return valid JSON and nothing else.
9. Summaries must only restate information present in the supplied text.
   Do not add definitions, gene expansions, mechanisms, or background
   knowledge that is not stated in the source.

10. Prefer representing explicitly stated biological processes such as
    inflammation, fibrosis, signaling, or remodeling as Pathway or Finding
    objects when they participate in a stated relationship.
"""


# ---------------------------------------------------------------------------
# Ollama helper
# ---------------------------------------------------------------------------

def _call_ollama(system_prompt: str, user_prompt: str) -> str:
    """
    Send a prompt to the locally running Ollama server.

    Returns the text generated by the model.
    """
    payload = {
        "model": OLLAMA_MODEL,
        "stream": False,
        "format": "json",
        "options": {
            "temperature": 0,
        },
        "messages": [
            {
                "role": "system",
                "content": system_prompt,
            },
            {
                "role": "user",
                "content": user_prompt,
            },
        ],
    }

    try:
        response = requests.post(
            OLLAMA_URL,
            json=payload,
            timeout=120,
        )

        response.raise_for_status()

    except requests.exceptions.ConnectionError as exc:
        raise RuntimeError(
            "Could not connect to Ollama. "
            "Make sure Ollama is installed and running."
        ) from exc

    except requests.exceptions.Timeout as exc:
        raise RuntimeError(
            "The local language model took too long to respond."
        ) from exc

    response_data = response.json()

    return response_data["message"]["content"]


# ---------------------------------------------------------------------------
# JSON parsing
# ---------------------------------------------------------------------------

def _parse_json_response(text: str) -> dict:
    """
    Parse JSON returned by the local language model.

    The cleanup also handles accidental markdown code fences.
    """

    cleaned = (
        text.replace("```json", "")
        .replace("```JSON", "")
        .replace("```", "")
        .strip()
    )

    start = cleaned.find("{")
    end = cleaned.rfind("}")

    if start != -1 and end != -1:
        cleaned = cleaned[start:end + 1]

    try:
        return json.loads(cleaned)

    except json.JSONDecodeError as exc:
        raise ValueError(
            "The language model returned invalid JSON."
        ) from exc

def _normalize_extraction(data: dict) -> dict:
    """
    Normalize local-model extraction output before schema validation.

    Small local language models may omit optional descriptive fields
    or occasionally produce unsupported object and relationship types.
    Invalid graph elements are removed rather than silently converted
    into potentially incorrect biomedical claims.
    """

    allowed_object_types = {
        "Gene",
        "Drug",
        "Pathway",
        "Finding",
        "Hypothesis",
        "Disease",
    }

    allowed_relationship_types = {
        "SUPPORTS",
        "CONTRADICTS",
        "ASSOCIATED_WITH",
        "MEASURES",
        "TARGETS",
        "PART_OF",
    }

    normalized_objects = []

    for obj in data.get("objects", []):
        if not all(
            key in obj
            for key in ("tempId", "type", "name")
        ):
            continue

        if obj["type"] not in allowed_object_types:
            continue

        normalized_objects.append({
            "tempId": obj["tempId"],
            "type": obj["type"],
            "name": obj["name"],
            "summary": obj.get("summary", ""),
        })

    valid_ids = {
        obj["tempId"]
        for obj in normalized_objects
    }

    normalized_relationships = []

    for relationship in data.get("relationships", []):
        if not all(
            key in relationship
            for key in ("from", "to", "type")
        ):
            continue

        if relationship["type"] not in allowed_relationship_types:
            continue

        if (
            relationship["from"] not in valid_ids
            or relationship["to"] not in valid_ids
        ):
            continue

        if relationship["from"] == relationship["to"]:
            continue

        normalized_relationships.append({
            "from": relationship["from"],
            "to": relationship["to"],
            "type": relationship["type"],
        })

    return {
        "title": data.get("title", "Untitled excerpt"),
        "objects": normalized_objects,
        "relationships": normalized_relationships,
    }

# ---------------------------------------------------------------------------
# Public extraction function
# ---------------------------------------------------------------------------

def extract_entities(text: str) -> ExtractionResult:
    """
    Extract biomedical entities and relationships from scientific text.

    Parameters
    ----------
    text:
        Scientific abstract, excerpt, or other biomedical text.

    Returns
    -------
    ExtractionResult
        Structured title, biomedical objects, and relationships.
    """

    if not text or not text.strip():
        raise ValueError("Input text cannot be empty.")



    response_text = _call_ollama(
        system_prompt=EXTRACTION_PROMPT,
        user_prompt=text.strip(),
    )

    parsed = _parse_json_response(response_text)
    parsed = _normalize_extraction(parsed)

    try:
        return ExtractionResult.model_validate(parsed)

    except Exception as exc:
        raise ValueError(
            "The extracted data did not match the BioOS graph schema."
        ) from exc 

