"""
Graph-grounded question answering for BioOS.

A locally running language model receives only the research context
retrieved from the BioOS graph and generates a grounded answer.
"""
import json
import os
import re
from pathlib import Path

import requests
from dotenv import load_dotenv

from schemas import AskResponse


# ---------------------------------------------------------------------------
# Environment configuration
# ---------------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent
ENV_PATH = BASE_DIR / ".env"

load_dotenv(ENV_PATH)


# ---------------------------------------------------------------------------
# Ollama configuration
# ---------------------------------------------------------------------------

OLLAMA_URL = os.getenv(
    "OLLAMA_URL",
    "http://localhost:11434/api/chat"
)

OLLAMA_MODEL = os.getenv(
    "OLLAMA_MODEL",
    "gemma3:4b"
)

# ---------------------------------------------------------------------------
# Reasoning prompt
# ---------------------------------------------------------------------------

REASONING_PROMPT = """
You are BioOS, a biomedical research assistant.

Answer the user's question ONLY using the provided research graph context.

Rules:

1. Do not introduce claims unsupported by the supplied context.

2. If the graph does not contain enough information to answer the question,
   explicitly say that the available research graph is insufficient.

3. Be concise. Keep the answer under 90 words.

4. Whenever you reference an object from the graph, wrap its EXACT name
   in double brackets.

Example:

[[SPP1]] is associated with [[Fibrotic remodeling]].

5. The "referenced" list must contain ONLY the exact object names that
   appear inside double brackets in the answer.

For example, if the answer contains:

[[SPP1]] and [[Fibrotic remodeling]]

then return:

"referenced": [
    "SPP1",
    "Fibrotic remodeling"
]

Do NOT add object types such as "Gene", "Disease", or "Pathway"
to names in the referenced list.

Respond with STRICT JSON ONLY using this schema:

{
  "answer": "answer containing [[Object Name]] references",
  "referenced": [
    "Object Name 1",
    "Object Name 2"
  ]
}

Do not include markdown fences, commentary, or text outside the JSON.
"""


# ---------------------------------------------------------------------------
# Ollama helper
# ---------------------------------------------------------------------------

def _call_ollama(system_prompt: str, user_prompt: str) -> str:
    """
    Send a prompt to the locally running Ollama server.

    Returns the text generated by the model.
    """

    payload = {
        "model": OLLAMA_MODEL,
        "stream": False,
        "format": "json",
        "options": {
            "temperature": 0,
        },
        "messages": [
            {
                "role": "system",
                "content": system_prompt,
            },
            {
                "role": "user",
                "content": user_prompt,
            },
        ],
    }

    try:
        response = requests.post(
            OLLAMA_URL,
            json=payload,
            timeout=120,
        )

        response.raise_for_status()

    except requests.exceptions.ConnectionError as exc:
        raise RuntimeError(
            "Could not connect to Ollama. "
            "Make sure Ollama is installed and running."
        ) from exc

    except requests.exceptions.Timeout as exc:
        raise RuntimeError(
            "The local language model took too long to respond."
        ) from exc

    response_data = response.json()

    return response_data["message"]["content"]


# ---------------------------------------------------------------------------
# JSON parsing
# ---------------------------------------------------------------------------

def _parse_json_response(text: str) -> dict:
    """Parse JSON returned by the local language model."""

    cleaned = (
        text.replace("```json", "")
        .replace("```JSON", "")
        .replace("```", "")
        .strip()
    )

    start = cleaned.find("{")
    end = cleaned.rfind("}")

    if start != -1 and end != -1:
        cleaned = cleaned[start:end + 1]

    try:
        return json.loads(cleaned)

    except json.JSONDecodeError as exc:
        raise ValueError(
            "The language model returned invalid JSON."
        ) from exc


# ---------------------------------------------------------------------------
# Response normalization
# ---------------------------------------------------------------------------

def _normalize_answer(data: dict) -> dict:
    """
    Derive graph references from [[...]] markers in the answer.

    Relationship labels accidentally wrapped by the local model
    are excluded from the referenced-object list.
    """

    answer = str(
        data.get("answer", "")
    ).strip()

    references = re.findall(
        r"\[\[(.*?)\]\]",
        answer,
    )

    relationship_types = {
        "MENTIONS",
        "SUPPORTS",
        "CONTRADICTS",
        "ASSOCIATED_WITH",
        "MEASURES",
        "TARGETS",
        "PART_OF",
        "RELATES_TO",
        "DERIVED_FROM",
    }

    unique_references = []

    for reference in references:
        reference = reference.strip()

        if not reference:
            continue

        if reference in relationship_types:
            continue

        if reference not in unique_references:
            unique_references.append(
                reference
            )

    return {
        "answer": answer,
        "referenced": unique_references,
    }


# ---------------------------------------------------------------------------
# Public reasoning function
# ---------------------------------------------------------------------------

def answer_from_graph(
    question: str,
    context: str,
) -> AskResponse:
    """
    Generate an answer grounded in retrieved research graph context.

    Parameters
    ----------
    question:
        Research question submitted by the user.

    context:
        Serialized subgraph produced by the retrieval pipeline.

    Returns
    -------
    AskResponse
        Grounded answer and names of referenced graph objects.
    """

    if not question or not question.strip():
        raise ValueError(
            "Question cannot be empty."
        )

    if not context or not context.strip():
        raise ValueError(
            "Graph context cannot be empty."
        )

    user_prompt = f"""
RESEARCH GRAPH CONTEXT:

{context}


QUESTION:

{question.strip()}
"""

    response_text = _call_ollama(
        system_prompt=REASONING_PROMPT,
        user_prompt=user_prompt,
    )

    parsed = _parse_json_response(
        response_text
    )

    parsed = _normalize_answer(
        parsed
    )

    try:
        return AskResponse.model_validate(
            parsed
        )

    except Exception as exc:
        raise ValueError(
            "The generated answer did not match "
            "the BioOS response schema."
        ) from exc